### PR TITLE
ZED-157 Function to update color's typos on all horses

### PR DESCRIPTION
**Pull request by aguxez**
At the moment we update color's typos before outputting them. This function will update the records with typos.

### CODE REVIEW

**Comment by girishramnani** [comment]
Maybe we could consider using `edit distance` to check better typos maybe using a library
https://github.com/lexmag/simetric

**Comment by aguxez** [comment]
Why do you think we should use it? I don't think we should add a library for it. We already know the typos which are those 4 colors. What use case we would have for it? Or where would be covered by the library?

**Comment by girishramnani** [comment]
Other typos are also covered if we use edit distance but if you feel we don't need something like then it's fine too.

**Comment by aguxez** [comment]
Yeah I don't think it is necessary right now but I see the utility

**Pull request merged**
